substitutions:
  node_name: blinds1
  friendly_name: Living Room Blinds

esphome:
  name: $node_name
  friendly_name: $friendly_name

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  # level: DEBUG

api:
  encryption:
    key: "KEY"

  services:
    - service: move_down_left
      variables:
        value: int
      then:
        - cover.move_down:
            id: left
            value: !lambda 'return value;'
    - service: move_down_right
      variables:
        value: int
      then:
        - cover.move_down:
            id: right
            value: !lambda 'return value;'

ota:
  password: "PASSWORD"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Blinds1 Fallback Hotspot"
    password: "PASSWORD"

captive_portal:

external_components:
  - source:
      type: git
      url: https://github.com/strange-v/mature_blinds
      ref: main
    components: [ mature_blinds ]

status_led:
  pin: 2

uart:
  tx_pin: 4
  rx_pin: 5
  baud_rate: 115200

output:
  - platform: gpio
    pin: 16
    id: en_pin
    inverted: true

cover:
  - platform: mature_blinds
    id: left
    name: Left Blinds
    # en_pin: 16
    dir_pin: 17
    step_pin: 25
    diag_pin:
      number: 33
      mode:
        input: true
    address: 0
    r_sense: 0.11
    rms_current: 50
    acceleration: 10000
    speed_in_us: 60
    stall_value: 0
    invert_rotation: false
    full_distance_in_steps: 990000
    homing_gap_in_steps: 5000
    on_before_start:
      then:
        lambda: |-
          id(en_pin).turn_on();
    on_after_stop:
      then:
        - delay: 5s
        - lambda: |-
            if (id(left).current_operation == COVER_OPERATION_IDLE && id(right).current_operation == COVER_OPERATION_IDLE) {
              id(en_pin).turn_off();
            }

  - platform: mature_blinds
    id: right
    name: Right Blinds
    # en_pin: 16
    dir_pin: 18
    step_pin: 23
    diag_pin:
      number: 34
      mode:
        input: true
    address: 1
    r_sense: 0.11
    rms_current: 50
    acceleration: 10000
    speed_in_us: 57
    stall_value: 0
    invert_rotation: true
    full_distance_in_steps: 1040000
    homing_gap_in_steps: 5000
    on_before_start:
      then:
        lambda: |-
          id(en_pin).turn_on();
    on_after_stop:
      then:
        lambda: |-
          if (id(left).current_operation == COVER_OPERATION_IDLE && id(right).current_operation == COVER_OPERATION_IDLE) {
            id(en_pin).turn_off();
          }

button:
  - platform: template
    name: Home
    id: home
    on_press:
      then:
        - cover.home: left
        - cover.home: right